// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Error": {
    "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
    "title": "Something went wrong!"
  },
  "IndexPage": {
    "description": "My name is Harun Dastekin, I'm 36 years old and I was born and raised in Berlin-Neukölln - in the Schiller neighbourhood to be precise.Today I live with my wife and my little daughter at the other end of Neukölln, in Gropiusstadt. The three of us live in a high-rise estate, in a cosy two-bedroom flat that has become our home despite its high-rise image.I got married in 2016 and became a father in 2021 - two formative milestones in my life.I recently joined the DRV Bund as a test developer in Team F and am looking forward to getting to know you and the work here better.",
    "title": "Harun Dastekin"
  },
  "LocaleLayout": {
    "title": "Harun Dastekin"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, de {🇩🇪 Deutsch} en {🇺🇸 English} other {Unknown}}"
  },
  "Manifest": {
    "name": "Harun Dastekin"
  },
  "Navigation": {
    "home": "Home",
    "job": "Career Path",
    "private": "Private Life"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "PageLayout": {
    "links": {
      "docs": {
        "description": "Learn more about me on my website.",
        "href": "https://www.dastekin.de/",
        "title": "Homepage"
      },
      "source": {
        "description": "Browse the source code of my self-introduction on GitHub.",
        "href": "https://github.com/hdi10/selbstvorstellung_me_TeamF",
        "title": "Source code"
      }
    }
  },
  "JobPage": {
    "description": "<p>My first job in the public sector was at Stromnetz Berlin. There, I worked in line information and route management.</p><p>In addition to my professional activities, I was always involved in voluntary work - these experiences were equally enriching for me both personally and professionally.</p><p>I then moved to a small IT company called Entraserv, where I worked as an IT consultant/software developer. My focus was on converting an ERP system for medium-sized companies into a mobile application.</p><p>Before joining the DRV Bund, I worked at Toll Collect as a software developer and test automation engineer - an exciting period in which I was able to further expand and deepen my technical expertise.</p>",
    "title": "My professional career"
  },
  "PrivatePage": {
    "description": "<p>We are a small family of three: my daughter is almost four years old and keeps us on our toes. My wife works as a planning engineer in a private engineering office - so we complement each other quite well: technology on both sides, but in completely different areas.</p><p>When there is time left over from family and work, I am interested in software projects, technology trends - or simply use the rare quiet minutes for a walk or a good chat.</p>",
    "title": "My private life"
  }
};
export default messages;